/*var secondsInAMinute = 60;
var minutesInAnHour = secondsInAMinute * 60;
var hoursInADay = minutesInAnHour * 24;
var daysInAYear = hoursInADay * 365;
var age = daysInAYear * 11;
console.log(age);

var balloons = 100;
balloons /= 4;
console.log(balloons);

var string = "hElLo tHerE, I aM kEnObi!";
string[0].toUpperCase() + string.slice(1).toLowerCase();
console.log(string);
*/
var names = [
"shit",
    "face",
    "hair",
    "alphabet",
    "advance",
    "aircraft construction",
    "autosave",
    "aggregation",
    "algae",
    "desire",
    "bazaar",
    "play",
    "batik",
    "grunting",
    "bearish",
    "beet harvesting",
    "swelling",
    "budgeting",
    "lodging",
    "kibchenya",
    "kiwi",
    "ring",
    "ring",
    "kimono",
    "movie",
    "tow",
    "slip",
    "swallow",
    "Cossacking",
    "kid",
    "kiddy",
    "copying",
    "rudder",
    "feeding",
    "feed production",
    "kingdom",
    "kingdoms",
    "coronation",
    "corsairs",
    "quotation",
    "crab",
    "horizon",
    "crossbreed",
    "lion cub",
    "lacing",
    "saddlery",
    "hunting",
    "logarithmics",
    "logarithm",
    "spooning",
    "wickerwork",
    "vine walking",
    "viticulture",
    "softness",
    "meat",
    "poppy",
    "meta-knowledge",
    "Monaco",
    "population",
    "start",
    "misunderstanding",
    "digging",
    "innovation",
    "infidelity",
    "New Year",
    "house warming",
    "deforestation",
    "review",
    "baring",
    "bust",
    "revival",
    "armament"
];
var howwhat = [
"beans",
    "real anthem",
    "pimples",
    "absenteeism",
    "absorber",
    "abutilon",
    "motoring",
    "highway",
    "atheist",
    "atherosclerosis",
    "atoll",
    "achromatism",
    "acetone",
    "rich evening",
    "ballast",
    "canopy",
    "banyak",
    "launch",
    "watt",
    "vatornik",
    "fireman",
    "I / O",
    "Vedism",
    "evening performance",
    "exhibition-fair",
    "viaduct",
    "video clip",
    "video",
    "Almighty City",
    "gas",
    "waiter",
    "helium",
    "Hertz",
    "hyperpurism",
    "hyponym",
    "Honduras",
    "pot",
    "grotto",
    "screw",
    "geluch",
    "court",
    "nine",
    "deodorant spray",
    "demarketing",
    "deplasmolysis",
    "part-time deputy",
    "sofa",
    "diploma",
    "expert teacher",
    "element",
    "elitism",
    "erg",
    "effect",
    "stallion",
    "fat resistant",
    "acorn",
    "zenith",
    "vision",
    "sol-gel",
    "priest",
    "land surveyor",
    "infante",
    "eater",
    "eater",
    "hedgehog",
    "cat",
    "boar",
    "boar",
    "squash",
    "cabernet",
    "cabotage",
    "cabochon",
    "cabriolet"
];
var how = [
    "as",
    "as if",
    "looks like",
    "roll on",
];

document.getElementById('button').onclick = function() {
    let callingField = document.getElementById('calling-field');
    let out = '';
    out += `<p class="alertName" role="alert">${["Your", names[Math.floor(Math.random() * 75)], how[Math.floor(Math.random() * 4)], howwhat[Math.floor(Math.random() * 74)] + "!!!"].join(" ")}</p>`;
    callingField.innerHTML = out;
}